import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist_Mono, Inter, Playfair_Display } from "next/font/google";
import { AppQueryProvider } from "@/components/providers/query-provider";
import "./globals.css";
import { dark } from '@clerk/ui/themes'


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
     theme: dark,
   }}>
      <html lang="en">
        <body
          className={`${inter.variable} ${playfair.variable} ${geistMono.variable} antialiased`}
        >
          <AppQueryProvider>{children}</AppQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
